Kegiatan/urls.py
from django.urls import path

from .views import list_kegiatan,tambah_peserta,tambah_kegiatan

app_name = 'Kegiatan'


urlpatterns = [

    path('', list_kegiatan , name = 'list'),
    path('tambahpeserta', tambah_peserta, name = 'tambahpeserta'),
    path('tambahkegiatan', tambah_kegiatan, name = 'tambahkegiatan'),
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('', views.webpage1, name='webpage1'),
    
    
]

tugas6ppwwow/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('kegiatan/',include('Kegiatan.urls',namespace = 'templates'))
]

Kegiatan/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama_kegiatan= models.CharField(max_length=30)
    def __str__(self):
        return self.nama_kegiatan

class Peserta(models.Model):
    nama_peserta = models.CharField(max_length=30)
    kegiatan = models.ForeignKey(Kegiatan,null = True, on_delete= models.SET_NULL)

    def __str__(self):
        return self.nama_peserta
    

home/models.py
from django.db import models

# Create your models here.

    

Kegiatan/forms.py
from django import forms
from .models import Kegiatan, Peserta

class formKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields ="__all__"
    

class formPeserta(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = "__all__"

home/forms.py
from django import forms
from .models import *

		

Kegiatan/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan,Peserta
from .forms import formKegiatan,formPeserta


def list_kegiatan(request):
    list_kegiatan = Kegiatan.objects.all()
    data_kegiatan = []
    for kegiatan in list_kegiatan:
        list_peserta = Peserta.objects.filter(kegiatan=kegiatan)
        data_peserta = []
        for peserta in list_peserta:
            data_peserta.append(peserta)
        data_kegiatan.append((kegiatan,data_peserta))
    context = {'data_kegiatan':data_kegiatan,'number':5}
    return render(request,'kegiatan.html',context)

def tambah_peserta(request):
    form = formPeserta()
    if (form.is_valid and request.method == 'POST'):
        form = formPeserta(request.POST)
        form.save()
        return redirect('/kegiatan')
    context = {'form':form,'number':5}
    return render(request,'tambahpeserta.html',context)

def tambah_kegiatan(request):
    form = formKegiatan()
    if (form.is_valid and request.method == 'POST'):
        form = formKegiatan(request.POST)
        form.save()
        return redirect('/kegiatan')

    context = {'form':form,'number':5}
    
    return render(request,'tambahkegiatan.html',context)

home/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import *
from .forms import *

def webpage1(request):
    return render(request, 'home/pageSelamatDatang.html')


    

Kegiatan/templates/kegiatan.html
<!doctype html>
<html lang="en">
  {% extends "home/base.html" %}
  {% load static %}
  {% block content %}
  <link rel="stylesheet" href="{% static 'css\style.css' %}">
  
  <main>
    <section class="section-1">
        <br>
      <div class = "container text-center">

        <h1 class="text-center">
            Daftar Kegiatan
        </h1>
          <div class="row">

            {% for i in data_kegiatan %}
              <div class="card" style="width: 50%;">
                  <div class="card-body">
                    
                    <h5 class="card-title mb-3">{{i.0.nama_kegiatan}}</h5>
                    <p class="card-text">
                        {% for a in i.1 %}
                        <div>{{a.nama_peserta}}</div>
                        {% endfor %}
                        </p>
                        
                        
                </div>
          </div>
          {% endfor %}
          
        </div>
        <br>
        <div class="text-center">
          <a class="btn btn-sm btn-info" href="{% url 'templates:tambahkegiatan' %}">Tambah Kegiatan</a>
          
          <a class="btn btn-sm btn-info" href="{% url 'templates:tambahpeserta' %}">Tambah Peserta</a>
        </div>
        
        <br><br><br><br><br><br>
    </div>
</div>
    
  </main>
{% endblock %}

Kegiatan/templates/tambahkegiatan.html
{% extends "home/base.html" %}
  {% load static %}
  {% block content %}
  <link rel="stylesheet" href="{% static 'css\style.css' %}">

  
  
<form action="" method="post">
    {% csrf_token %}
    <br><br><br><br><br>
    <table class="table">
      {% csrf_token %}
      <thead class="thead-dark">
        <tr>
          <th scope="row">Keterangan</th>
          <th scope="row">Nama Peserta</th>
          
        </tr>
      </thead>
      <tbody>
        <tr>
          {{form}}
        </tr>
        <tr>
      </table>
<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Tambah">
<a class="btn btn-lg btn-block btn-danger" href="/kegiatan">Batal</a>
</form>
{% endblock %}

Kegiatan/templates/tambahpeserta.html
{% extends "home/base.html" %}
  {% load static %}
  
  {% block content %}
  <link rel="stylesheet" href="{% static 'css\style.css' %}">
<form action="" method="post">
    {% csrf_token %}
    <br><br><br><br><br>
    <table class="table">
      {% csrf_token %}
      <thead class="thead-dark">
        <tr>
          <th scope="row">Keterangan</th>
          <th scope="row">Nama Peserta</th>
          
        </tr>
      </thead>
      <tbody>
        <tr>
          {{form}}
        </tr>
        <tr>
      </table>
<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Tambah">
<a class="btn btn-lg btn-block btn-danger" href="/kegiatan">Batal</a>
</form>
{% endblock %}

home/templates/home/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css\style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block meta %}
    {% endblock meta %}
    <title>Tugas 6 PPW Ravi</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-transparent fixed-top">
      <div class="container">
          <a class="navbar-brand">Tugas 6 PPW Ravi</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarUtama">
          <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'webpage1' %}">Welcome</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'templates:list' %}">Lihat Kegiatan</a>
          </li>
        </ul>
      </div>
      </div>  
    </nav>
    <main role="main" class="container">
      <div>
        <div >
          {% block content %}{% endblock %}
        </div>
        <div > 
        </div>
      </div>
    </main>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/home/pageSelamatDatang.html
{% extends 'home/base.html' %}
{% block content %}
{% load static %}
  <body>
      <div class="jumbotron bg-transparent" style="margin-top: 150px">
        <div class="container"></div>
          <h1 style= "text-align: center" class="display-4">Assalamualaikum<br>Perkenalkan nama saya 
            Muhammad Ravi
            <br>Selamat datang di website saya &#128512</h1>
            <br>
            <div class="text-center">
              <a class="btn btn-primary btn-lg" style= "align= center" href="/kegiatan/"button">Mulai lihat kegiatan</a>
            </div>
        </div>
    </div>
    {% endblock %}